import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import ViteRestart from 'vite-plugin-restart';

export default defineConfig({
  plugins: [
    vue(),
    // Keep the browser in sync with generated / static artifacts so the user
    // never has to manually restart the dev server. Source edits in `src/`
    // still use normal Vite HMR.
    //
    // `restart` — files imported into the app as ES modules. Vite's HMR can
    // silently desync on these (esp. the ~10MB metadata.json and the
    // regenerate-and-rewrite positions tables), so we do a clean server
    // restart that re-transforms from scratch. The restart also re-serves
    // public/icons fresh, fixing icon staleness that build:data's `rmSync`
    // causes.
    //   - metadata.json / recipes.json : regenerated by `npm run build:data`
    //   - positions-*.js               : regenerated by `npm run generate-positions`
    //     (previously NOT watched -> edits relied on fragile HMR and sometimes
    //     failed to reload).
    //
    // `reload` — static public assets referenced by URL (icons, guide HTML,
    // changelog). A full page reload is enough; no need to re-parse modules.
    //
    // Paths are explicit files + narrow globs (not a bare dir). The old ENOSPC
    // worry no longer applies: inotify headroom here is ~65k watches and the
    // project uses well under 1k, so `public/**` (~675 icon files) is safe.
    //
    // `contentCheck: false` (default true) forces a trigger on EVERY regen, not
    // only when content changed — also catches icon-only / rename changes.
    ViteRestart({
      restart: [
        'parser/data/metadata.json',
        'parser/data/recipes.json',
        'parser/data/positions-stockpile.js',
        'parser/data/positions-inventory.js',
      ],
      reload: ['public/**'],
      contentCheck: false,
    }),
  ],
});